Now default Main file runs correctly(if we use green 'run' button in Intelij IDEA). Create all Pokemons and their Moves. TODO: Effects for all Moves, FIXME: 'mvn clean install' 'java -jar .\target\labproject-1.0-jar-with-dependencies.jar' causes an error 'Caused by: java.lang.NoClassDefFoundError: ru/ifmo/se/pokemon/Pokemon'